config/routes.rb
Rails.application.routes.draw do


  # #comfy_route :cms_admin, :path => '/admin'
  # mount RailsEmailPreview::Engine, at: 'emails'
  resources :products
  resources :profiles
  resources :matters, :tasks, :issues, :trainings, :users, :offices do
    resources :comments, :attachments, :tasks, :issues
  end

  resources :job_titles, :business_units, :profit_centers, :departments, :divisions, :functions, :locations, :segments do
    resources :comments, :attachments, :tasks, :issues
  end


  resources :chat_rooms, only: [:new, :create, :show, :index]
  resources :friendships, only: [:create, :update, :destroy]

  mount ActionCable.server => '/cable'

  get 'activities/index'
  resources :public_activities
  get 'attestation/:policy_attestation_id', to: 'attestations#show', as: 'attestation_path'
  get 'taskable/:taskable_type/:taskable_id/tasks', to: 'tasks#index', as: 'taskable_tasks_path'
  get 'taskable/:taskable_type/:taskable_id/task_board', to: 'tasks#task_board', as: 'taskable_task_board_path'
  get 'activities/index', as: :public_activity_orm_active_record_activity_comment_path
  get 'tasks/task_board', to: 'tasks#task_board'
  get 'entries/index'

  post 'users/:item/:role/:user', to: 'users#role', as: 'user_role_path'

  post 'matters/:id', to: 'matters#update', as: 'update_matter_tasks_path'

  post 'user_assignments/:id/:role', to: 'user_assignments#update', as: 'update_user_role_path'
  delete 'user_assignments/:id', to: 'user_assignments#destroy', as: 'destroy_user_role_path'

  post 'training_users/:id/:role', to: 'training_users#update', as: 'update_training_user_role_path'
  delete 'training_users/:id', to: 'training_users#destroy', as: 'destroy_training_user_role_path'


  post 'follow/:item/', to: 'follows#create', as: 'item_follow_path'
  delete 'unfollow/:item', to: 'follows#destroy', as: 'item_unfollow_path'
  get 'entries/show'
  get "rss_feeds/update_feeds"
  resources :entries, only: [:index, :show]
  # notify_to :users, controller: 'users/notifications'

  notify_to :users, with_devise: :users

  resources :rss_feeds do
    member do
     resources :entries, only: [:index, :show]
    end
  end
  devise_for :user, skip: [:sessions]

  # devise_for :user, controllers: {
  #   confirmations: 'devise/confirmations',
  #   passwords: 'devise/passwords',
  #   registrations: 'devise/registrations',
  #   sessions: 'devise/sessions',
  #   unlocks: 'devise/unlocks',
  # }, skip: [:sessions]

  # devise_for :user

  # custom routes for users
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    # delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'register' => 'devise/registrations#new'
    # root to: "devise/sessions#new"
  end


  unauthenticated do
   root :to => 'devise/sessions#new'
  end

  authenticated do
    root :to => 'matters#index'
  end

  resources :attachments, able: 'attachable'
  resources :comments, able: 'commentable'

  resources :companies
  resources :policies
  resources :divisions
  resources :departments
  resources :functions


  # get 'user/show'
  resources :offices
  root to: 'home#home'




end

app/models/user_groups/office.rb
class Office < ApplicationRecord
  include UserGroup
  belongs_to :location, optional: true
  has_many :users
  has_many :offices, through: :users
  has_many :functions, through: :users
  has_many :departments, through: :users
  has_many :divisions, through: :users
  has_many :profit_centers, through: :users
  has_one :operating_company, through: :users
  has_one :business_units, through: :users
  has_one :companies, through: :users

end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    items = Office.includes(:profile)
    respond_to do |format|
      format.html { render "layouts/index", locals: {items: items, items_name: 'offices'}  }
      format.json { render json: @items.tokens(params[:q]) }
    end
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
     @activities = @office.group_activities
                      .paginate(:page => params[:page], :per_page => 10000)
                      .group_by {|t| t.created_at.to_date }
    respond_to do |format|
      format.html { render "layouts/show", locals: {item: @office}  }
      format.json
    end
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.fetch(:office, {})
    end
end

app/helpers/office_helper.rb
module OfficeHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= simple_form_for(@office) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/offices/_index.html.erb
<div class="row">
<div class="col-lg-11">
<div class="ibox float-e-margins">
<div class="ibox-title">
    <div class="ibox-tools">
        <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
        </a>
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-wrench"></i>
        </a>
        <ul class="dropdown-menu dropdown-item">
            <li>
                <a href="#">Config option 1</a>
            </li>
            <li>
                <a href="#">Config option 2</a>
            </li>
        </ul>
        <a class="close-link">
            <i class="fa fa-times"></i>
        </a>
    </div>
</div>

<div class="ibox-content">
<table class="table table-striped table-bordered table-hover dataTables-example1">

    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>

    <tbody>
        <% items.each do |item| %>
        <% unless item.name.nil? %>
            <tr>
                <td><%= link_to item.name, item %></td>
            </tr>
        <% end %>
        <% end %>
    </tbody>


</table>
</div>
</div>
</div>
</div>

app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offices</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= link_to 'Show', office %></td>
        <td><%= link_to 'Edit', edit_office_path(office) %></td>
        <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Office', new_office_path %>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>


<%= render partial: "partials/show", locals: {item: @office} %>