config/routes.rb
Rails.application.routes.draw do


  # #comfy_route :cms_admin, :path => '/admin'
  # mount RailsEmailPreview::Engine, at: 'emails'
  resources :products
  resources :profiles
  resources :matters, :tasks, :issues, :trainings, :users, :offices do
    resources :comments, :attachments, :tasks, :issues
  end

  resources :job_titles, :business_units, :profit_centers, :departments, :divisions, :functions, :locations, :segments do
    resources :comments, :attachments, :tasks, :issues
  end


  resources :chat_rooms, only: [:new, :create, :show, :index]
  resources :friendships, only: [:create, :update, :destroy]

  mount ActionCable.server => '/cable'

  get 'activities/index'
  resources :public_activities
  get 'attestation/:policy_attestation_id', to: 'attestations#show', as: 'attestation_path'
  get 'taskable/:taskable_type/:taskable_id/tasks', to: 'tasks#index', as: 'taskable_tasks_path'
  get 'taskable/:taskable_type/:taskable_id/task_board', to: 'tasks#task_board', as: 'taskable_task_board_path'
  get 'activities/index', as: :public_activity_orm_active_record_activity_comment_path
  get 'tasks/task_board', to: 'tasks#task_board'
  get 'entries/index'

  post 'users/:item/:role/:user', to: 'users#role', as: 'user_role_path'

  post 'matters/:id', to: 'matters#update', as: 'update_matter_tasks_path'

  post 'user_assignments/:id/:role', to: 'user_assignments#update', as: 'update_user_role_path'
  delete 'user_assignments/:id', to: 'user_assignments#destroy', as: 'destroy_user_role_path'

  post 'training_users/:id/:role', to: 'training_users#update', as: 'update_training_user_role_path'
  delete 'training_users/:id', to: 'training_users#destroy', as: 'destroy_training_user_role_path'


  post 'follow/:item/', to: 'follows#create', as: 'item_follow_path'
  delete 'unfollow/:item', to: 'follows#destroy', as: 'item_unfollow_path'
  get 'entries/show'
  get "rss_feeds/update_feeds"
  resources :entries, only: [:index, :show]
  # notify_to :users, controller: 'users/notifications'

  notify_to :users, with_devise: :users

  resources :rss_feeds do
    member do
     resources :entries, only: [:index, :show]
    end
  end
  devise_for :user, skip: [:sessions]

  # devise_for :user, controllers: {
  #   confirmations: 'devise/confirmations',
  #   passwords: 'devise/passwords',
  #   registrations: 'devise/registrations',
  #   sessions: 'devise/sessions',
  #   unlocks: 'devise/unlocks',
  # }, skip: [:sessions]

  # devise_for :user

  # custom routes for users
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    # delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'register' => 'devise/registrations#new'
    # root to: "devise/sessions#new"
  end


  unauthenticated do
   root :to => 'devise/sessions#new'
  end

  authenticated do
    root :to => 'matters#index'
  end

  resources :attachments, able: 'attachable'
  resources :comments, able: 'commentable'

  resources :companies
  resources :policies
  resources :divisions
  resources :departments
  resources :functions


  # get 'user/show'
  resources :offices
  root to: 'home#home'




end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :user
  belongs_to :attachable, polymorphic: true
  searchkick
  include PublicActivity::Model
  tracked owner: Proc.new { |controller, model| controller.current_user ? controller.current_user : nil },
             title: Proc.new { |controller, model| model.file_file_name },
             recipient: Proc.new { |controller, model| model.attachable },
             :params => {
              :changes => Proc.new {|controller, model| model.changes.to_json}
          }

  has_attached_file :file
  validates_attachment_content_type :file, :content_type => ["application/pdf","application/vnd.ms-excel",
            "application/zip",
            "application/x-zip",
            "application/x-zip-compressed",
            "application/octet-stream",
            "application/vnd.ms-office",
            "application/msword",
             "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
             "application/msword",
             "application/mspowerpoint",
             "text/csv",
             "application/vnd.openxmlformats-officedocument.presentationml.presentation",
             "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
             "text/plain",
         	   "image/jpeg",
         	   "image/png",
         	   "image/gif"]



end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_owner
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index

  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show

  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json

  def create
    @attachment = @owner.attachments.new(attachment_params)
    @attachment.user = current_user
    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment.attachable, notice: 'Attachment was successfully created.' }
        format.json { render 'attachment.js.erb', locals: {attachment: @attachment, item: @owner } }
        format.js { render :attachment, locals: {attachment: @attachment, item: @owner } }
      else
        format.html { redirect_to able }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
        format.js { render :attachment, locals: {attachment: @attachment, item: @owner } }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @able, notice: 'Attachment was successfully updated.' }
        format.json { render 'attachment.js.erb', locals: {attachment: @attachment, item: @owner } }
        format.js { render :attachment, locals: {attachment: @attachment, item: @owner } }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
        format.js { render :attachment, locals: {attachment: @attachment, item: @owner } }
      end
    end
  end

  def set_owner
    params.each do |key, value|
     # target groups using regular expressions
     if (key.to_s.end_with? '_id')
      model = key.dup.gsub('_id', '').classify.constantize
      @owner = model.find(value)
     end

    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachable, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:file_file_name, :file_file_size, :file_content_type, :file)
    end


end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_attachments.html.erb
<a class="btn btn-xs btn-white btn-circle-xs pull-right", id="<%="button_#{attachment.id}" %>">X</a>
<li id="<%="delete_#{attachment.id}" %>" style="display: none">Are you sure you want to delete this file?
    <a><%= link_to "Yes", attachment_path(attachment), data: { confirm: 'Are you sure?' }, method: :delete %></a>
    <a href="#" id="<%="dont_delete_#{attachment.id}" %>"> No </a>
</li>

app/views/attachments/_form.html.erb
<%= form_for([item, item.attachments.new], html: { multipart: true, class: "dropzone"}) do |f|  %>
  <div class="fallback">
    <%= f.file_field :file %>
    <%= f.hidden_field :user, :value => current_user %>
    <br>
    <%= f.submit "Upload" %>
  </div>
<% end %>

<% content_for :javascript do %>
   <script type="text/javascript">

   $(document).ready(function(){
	// disable auto discover
	Dropzone.autoDiscover = false

	// grap our upload form by its id
	$('#new_attachment').dropzone({
		// restrict image size to a maximum 1MB
		maxFilesize: 100,
		// changed the passed param to one accepted by
		// our rails app
		paramName: "attachment[file]",

		// show remove links on each image upload
		addRemoveLinks: true,
		// if the upload was successful
		success: function(file, response){
			// find the remove button link of the uploaded file and give it an id
			// based of the fileID response from the server
			$(file.previewTemplate).find('.dz-remove').attr('id', response.fileID)
			// add the dz-success class (the green tick sign)
			$(file.previewElement).addClass("dz-success")
		},
		//when the remove button is clicked
		removedfile: function(file){
			// grap the id of the uploaded file we set earlier
			var id = $(file.previewTemplate).find('.dz-remove').attr('id')

			// make a DELETE ajax request to delete the file
			$.ajax({
				type: 'DELETE',
				url: '/attachments/' + id,
				success: function(data){
					console.log(data.message)
				}
			})
		}
	})
})

</script>
<% end %>

app/views/attachments/_remove.html.erb
<a class="btn btn-xs btn-white btn-circle-xs pull-right", id="<%="button_#{attachment.id}" %>">X</a>
<li id="<%="delete_#{attachment.id}" %>" style="display: none">Are you sure you want to delete this file?
    <a><%= link_to "Yes", attachment_path(attachment), data: { confirm: 'Are you sure?' }, method: :delete %></a>
    <a href="#" id="<%="dont_delete_#{attachment.id}" %>"> No </a>
</li>

app/views/attachments/attachment.js.erb
$("#attachments-list").html("<%= escape_javascript(render(partial: "partials/attachments.html.erb", locals: {item: item})) %>")

$(document).ready(function(){

      $('.delete_attachment').bind('ajax:success', function() {
              $(this).closest('li').fadeOut()
      })

 })

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attachments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>