config/routes.rb
Rails.application.routes.draw do


  # #comfy_route :cms_admin, :path => '/admin'
  # mount RailsEmailPreview::Engine, at: 'emails'
  resources :products
  resources :profiles
  resources :matters, :tasks, :issues, :trainings, :users, :offices do
    resources :comments, :attachments, :tasks, :issues
  end

  resources :job_titles, :business_units, :profit_centers, :departments, :divisions, :functions, :locations, :segments do
    resources :comments, :attachments, :tasks, :issues
  end


  resources :chat_rooms, only: [:new, :create, :show, :index]
  resources :friendships, only: [:create, :update, :destroy]

  mount ActionCable.server => '/cable'

  get 'activities/index'
  resources :public_activities
  get 'attestation/:policy_attestation_id', to: 'attestations#show', as: 'attestation_path'
  get 'taskable/:taskable_type/:taskable_id/tasks', to: 'tasks#index', as: 'taskable_tasks_path'
  get 'taskable/:taskable_type/:taskable_id/task_board', to: 'tasks#task_board', as: 'taskable_task_board_path'
  get 'activities/index', as: :public_activity_orm_active_record_activity_comment_path
  get 'tasks/task_board', to: 'tasks#task_board'
  get 'entries/index'

  post 'users/:item/:role/:user', to: 'users#role', as: 'user_role_path'

  post 'matters/:id', to: 'matters#update', as: 'update_matter_tasks_path'

  post 'user_assignments/:id/:role', to: 'user_assignments#update', as: 'update_user_role_path'
  delete 'user_assignments/:id', to: 'user_assignments#destroy', as: 'destroy_user_role_path'

  post 'training_users/:id/:role', to: 'training_users#update', as: 'update_training_user_role_path'
  delete 'training_users/:id', to: 'training_users#destroy', as: 'destroy_training_user_role_path'


  post 'follow/:item/', to: 'follows#create', as: 'item_follow_path'
  delete 'unfollow/:item', to: 'follows#destroy', as: 'item_unfollow_path'
  get 'entries/show'
  get "rss_feeds/update_feeds"
  resources :entries, only: [:index, :show]
  # notify_to :users, controller: 'users/notifications'

  notify_to :users, with_devise: :users

  resources :rss_feeds do
    member do
     resources :entries, only: [:index, :show]
    end
  end
  devise_for :user, skip: [:sessions]

  # devise_for :user, controllers: {
  #   confirmations: 'devise/confirmations',
  #   passwords: 'devise/passwords',
  #   registrations: 'devise/registrations',
  #   sessions: 'devise/sessions',
  #   unlocks: 'devise/unlocks',
  # }, skip: [:sessions]

  # devise_for :user

  # custom routes for users
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    # delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'register' => 'devise/registrations#new'
    # root to: "devise/sessions#new"
  end


  unauthenticated do
   root :to => 'devise/sessions#new'
  end

  authenticated do
    root :to => 'matters#index'
  end

  resources :attachments, able: 'attachable'
  resources :comments, able: 'commentable'

  resources :companies
  resources :policies
  resources :divisions
  resources :departments
  resources :functions


  # get 'user/show'
  resources :offices
  root to: 'home#home'




end

app/models/user_groups/business_unit.rb
class BusinessUnit < ApplicationRecord
    include UserGroup
    has_many :offices, through: :users
    has_many :locations, through: :offices
    has_many :functions, through: :users
    has_many :departments, through: :users

    has_many :profit_centers, through: :users
    has_one :operating_company, through: :users
    has_one :companies, through: :users

    belongs_to :segment, optional: true
    belongs_to :division, optional: true

    acts_as_follower
end

app/controllers/business_units_controller.rb
class BusinessUnitsController < ApplicationController
  before_action :set_business_unit, only: [:show, :edit, :update, :destroy]

  # GET /business_units
  # GET /business_units.json
  def index
    items = BusinessUnit.includes(:profile)
    respond_to do |format|
      format.html { render "layouts/index", locals: {items: @items, item_name: 'business_units'}  }
      format.json { render json: @items.tokens(params[:q]) }
    end
  end

  # GET /business_units/1
  # GET /business_units/1.json
  def show
    @activities = @business_unit.group_activities
                      .paginate(:page => params[:page], :per_page => 10000)
                      .group_by {|t| t.created_at.to_date }
    respond_to do |format|
      format.html { render "layouts/show", locals: {item: @business_unit}  }
      format.json 
    end
    respond_to do |format|
      format.html { render "layouts/show", locals: {item: @business_unit}  }
      format.json
    end
  end

  # GET /business_units/new
  def new
    @business_unit = BusinessUnit.new
  end

  # GET /business_units/1/edit
  def edit
  end

  # POST /business_units
  # POST /business_units.json
  def create
    @business_unit = BusinessUnit.new(business_unit_params)

    respond_to do |format|
      if @business_unit.save
        format.html { redirect_to @business_unit, notice: 'Business unit was successfully created.' }
        format.json { render :show, status: :created, location: @business_unit }
      else
        format.html { render :new }
        format.json { render json: @business_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_units/1
  # PATCH/PUT /business_units/1.json
  def update
    respond_to do |format|
      if @business_unit.update(business_unit_params)
        format.html { redirect_to @business_unit, notice: 'Business unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_unit }
      else
        format.html { render :edit }
        format.json { render json: @business_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_units/1
  # DELETE /business_units/1.json
  def destroy
    @business_unit.destroy
    respond_to do |format|
      format.html { redirect_to business_units_url, notice: 'Business unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_unit
      @business_unit = BusinessUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_unit_params
      params.require(:business_unit).permit(:name)
    end
end

app/helpers/business_units_helper.rb
module BusinessUnitsHelper
end

app/views/business_units/_form.html.erb
<%= simple_form_for(@business_unit) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/business_units/_index.html.erb
<div class="row">
<div class="col-lg-11">
<div class="ibox float-e-margins">
<div class="ibox-title">
    <div class="ibox-tools">
        <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
        </a>
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-wrench"></i>
        </a>
        <ul class="dropdown-menu dropdown-item">
            <li>
                <a href="#">Config option 1</a>
            </li>
            <li>
                <a href="#">Config option 2</a>
            </li>
        </ul>
        <a class="close-link">
            <i class="fa fa-times"></i>
        </a>
    </div>
</div>

<div class="ibox-content">
<table class="table table-striped table-bordered table-hover dataTables-example1">

    <thead>
        <tr>
            <th>Name</th>
            <th>Division</th>
        </tr>
    </thead>

    <tbody>
        <% items.each do |item| %>
        <% unless item.name.nil? %>
            <tr>
                <td><%= link_to item.name, item %></td>
                <td><%= link_to item.division_name, item.division unless item.division_name.nil? %></td>
            </tr>
        <% end %>
        <% end %>
    </tbody>


</table>
</div>
</div>
</div>
</div>

app/views/business_units/edit.html.erb
<h1>Editing Business Unit</h1>

<%= render 'form', business_unit: @business_unit %>

<%= link_to 'Show', @business_unit %> |
<%= link_to 'Back', business_units_path %>

app/views/business_units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Business Units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_units.each do |business_unit| %>
      <tr>
        <td><%= business_unit.name %></td>
        <td><%= link_to 'Show', business_unit %></td>
        <td><%= link_to 'Edit', edit_business_unit_path(business_unit) %></td>
        <td><%= link_to 'Destroy', business_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business Unit', new_business_unit_path %>

app/views/business_units/new.html.erb
<h1>New Business Unit</h1>

<%= render 'form', business_unit: @business_unit %>

<%= link_to 'Back', business_units_path %>

app/views/business_units/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: "partials/show", locals: {item: @business_unit} %>